### ISSUE TITLE
Better commands declarations

### ISSUE THREAD

**Issue by adamsky** [adamsky/outcome-sim#12]
Command declarations should change to something like this

```yaml
# list of commands for some state
commands:
  # declaration of an eval_string command
  - cmd: eval_string
    # first three args here are required
    left: @string_var
    operator: ==
    right: stringvariable
    # this is optional, it would break on false by default
    if_false: break
```
