### ISSUE TITLE
Processing external-write commands

### ISSUE THREAD

**Issue by adamsky** [adamsky/outcome-sim#17]
### Process external-write commands in the main thread

Processing of "external-write" commands (command at any one entity writing to any of the other entities' variables) has to be processed inside the main thread. This can be either done before or after processing the entity threads.

Either way this would need to be pointed out in the docs, that even though the commands in a state are laid out sequentially, the external-write operations will not follow that sequential order. One quick example:

```yaml
# example for the case where "external-write" commands are
# processed __before__ the entity-local-thread processing is started  
commands:
# set a local `message` to contain some important message
- cmd: set_string
  target: string/message
  value: "important message!"
# set `receiver` string in another entity ("e01003")
# to the value of the local `message`
- cmd: ext_set_string
  target: /region/e01003/generic/test_element/string/receiver
  source: string/message

# Even though the external-write command `ext_set_string` appears 
# after the local `set_string`, it's executed __before__.
# After this particular tick has been processed
# we end up with `receiver` string value not being "important message!".
# Instead it will contain whatever has been the value of `message` before
# we set it to "important message!".

```
